### ISSUE TITLE
Estimate a scalar for prior matrices

### ISSUE THREAD

**Issue by gaow** [stephenslab/mmbr#10]
The idea is that analogous to SuSiE's `estimate_prior_variance` we can also do something to "estimate" the number of mappable effects in a more principled way than ad hoc filtering by purity. It is appealing to have this feature in `mmbr`. However instead of fitting on and adjusting the entire prior matrices (mission impossible) we can instead introduce just a scalar, eg, change prior from `N(0, U)` to `N(0, pho * U)` where we estimate `pho`. 

This is a one dimension optimization problem [implemented here](https://github.com/gaow/mmbr/blob/ed7adbf1dc5e4f0c35990a461235be305019c2ee/R/bayesian_multivariate_regression.R#L101) for simple prior (not mixture prior). 

Here is a notebook to show it in action:

https://gaow.github.io/mmbr/prototypes/multivariate_est_prior.html

It appears to work but apparently very slow. 

Notice here I use `BFGS` method not `Brent` (as in SuSiE) because `Brent` requires specifying lower and upper bounds which I'm not sure what to set for here for upper bound. walltime for `BFGS` is 1.5 times of that for `Brent` anyways so both are considered slow.

To get it work for MASH prior there will be more challenges:

1. We will have to compute various inverses every iteration because the prior keeps changing -- currently we offer an option to compute inverses only once and use them for all iterations.
2. It's only going to be slower for MASH mixture prior.
3. We then have to code in R for the outer loop over J variables.

None of the problems above seems trivial.

**Comment by gaow** [comment]
I do, however, now implemented a [`simple` method](https://github.com/gaow/mmbr/blob/696a547263fc6dd1dd5cd3db5d2ab98629442810/R/mash_regression.R#L89) to at least compare with zero prior and decide what to use. This [helps with model misspecification](https://gaow.github.io/mvarbvs/analysis/20191204_Diagnosis.html#Estimate-prior-variance).

**Comment by gaow** [comment]
In light of #12 and discussion with Matthew, it may be feasible to optimizing the prior over a grid of, say 4 values. Essential #12 is to optimize over two values (0 and the default value). This will be less expensive than a full optimization. Although problems 1 above is till going to apply for MASH prior.

**Comment by stephens999** [comment]
I'll not sure if 1 above still applies for a grid... Can't you precompute for the grid?

**Comment by gaow** [comment]
> Can't you precompute for the grid?

Great point. I should have elaborated. When `sbhat` the standard error is different for all `J` SNP in an analysis (`J` can easily be >3000 in our case) then we have this issue of memory holding all those precomputed quantities: https://github.com/gaow/mmbr/issues/5#issue-426060464 (see the first point in the `Cons` section). Having to hold additional quantities for these grids makes it even worse. It might be safer as a result to not pre-compute.

**Comment by stephens999** [comment]
Is that still true if you standardize the snps? Isn't the se the same for every snp then?

**Comment by gaow** [comment]
> Is that still true if you standardize the snps? Isn't the se the same for every snp then?

@stephens999 It is absolutely true if the data is complete. When there is missing data however, which is the case for most of our current applications, there are some problems at least the way I currently scale them. Scaling for missing data case was what I wanted to discuss with you (in person) about. But before that I'll try to post some examples.

We definitely can implement the coarse grid method. It's just a matter of whether or not to automatically disable precomputed values some times -- a straightforward though not very elegant engineering issue.

**Comment by stephens999** [comment]
I see, yes, interesting. Let's talk in person.

**Comment by gaow** [comment]
@stephens999 @zouyuxin @pcarbo Before I close this ticket let me use the conversation as a quick update for new benchmark results after we implemented scalar estimate using EM method. The simulation scenarios are suggested by @stephens999 where we created 1) some artificial mixture of canonical matrices in MASH, as well as some pair-wise sharing and block sharing (eg brain vs non-brain) plus diagonal residual variance, and 2) using data driven priors learned from GTEx V8 (PCA + FLASH then ED), plus residual variance using estimated variance of the actual gene expression (realistic).

The overall conclusion is that:

1. under realistic (or at least non-trivial) simulation settings, being able to estimate mixture and weights for the signal and using that as the prior (in this case we use just oracle prior) performs best, followed by just using a naive mixture of canonical matrices and uniform weights as priors. Fixed effect (all shared prior) and random effects (using identity matrix) model don't perform well enough. 
2. using FLASH to estimate the residual covariance and fix it to FLASH estimate seems to be good enough compared to using oracle residual covariance.

Next steps:

1. Finalize on what to do with ED then run additional analysis using ED based prior, hoping it lies in between oracle and default naive mixture. 
2. Analyzing GTEx V8 data -- using new ED prior and weights. We can give it a go using our current missing data implementation (slightly wrong but empirically not wrong by too much), while trying to figure out better ways to do it.

## PIP calibration

### artificial mixture 
![pip1](https://user-images.githubusercontent.com/917985/81095736-70cdca80-8ed3-11ea-8932-f8aebb4d6e75.png)


### GTEx mixture

![pip2](https://user-images.githubusercontent.com/917985/81095767-77f4d880-8ed3-11ea-98e4-c4d54a4165fc.png)

## PR curves for PIP

### artificial mixture 

![pr1](https://user-images.githubusercontent.com/917985/81095802-80e5aa00-8ed3-11ea-9b6c-2427a957dc4f.png)


### GTEx mixture

![pr2](https://user-images.githubusercontent.com/917985/81095810-84793100-8ed3-11ea-901c-955e2e7cbfe7.png)


## Properties of CS

See it here: https://gaow.github.io/mvarbvs/analysis/20200430_MNM_Benchmark_CS.html

## Comparison with atlasqtl

`atlasqtl` has calibration issues ... not sure how to compare it given its problem. Here is result from artificial mixture scenario (top) and GTEx mixture (bottom):

![image](https://user-images.githubusercontent.com/917985/81096337-31ec4480-8ed4-11ea-82a4-f58c8cdbec2a.png)

**Comment by pcarbo** [comment]
@gaow Looks great. I don't see any major surprises, which is good.

To clarify, the "fixed effects" and "random effects" priors are just simple multivariate normal priors (*i.e.*, you do not use the mixture-of-normals prior)?

I suppose most of the "interesting" part of the FDR vs. power plot happens at FDR < 0.1, so you may want to zoom in on that so that we can see more clearly the differences.
