### ISSUE TITLE
An option to scale Y as well as input residual variance

### ISSUE THREAD

**Issue by gaow** [stephenslab/mmbr#25]
I've observed some cases in simulation studies that when variance of Y is very small the residual variance (denoted as V), using variance of Y, is also very small. That can lead to ill-conditioned matrix and numerical issues after. 

I was initially thinking of checking for such ill-conditioned input and report an error asking users to check their input Y or V whichever available. @zouyuxin suggests that instead we can standardize Y, and adjust the scale of input prior variance accordingly, to be consistent with rescaled Y. This should avoid the potential issues. 

@stephens999  @pcarbo @fmorgante any suggestions?

**Comment by pcarbo** [comment]
Could you give an example of what you mean by "variance of Y is very small"?

A covariance matrix with small variances is not necessarily ill-conditioned. e.g., `1e-256 * diag(2)` is perfectly well conditioned.

**Comment by gaow** [comment]
@pcarbo sure here is an example we ran into in a simulation data-set:

[Y_variance.tar.gz](https://github.com/stephenslab/mmbr/files/4279280/Y_variance.tar.gz)

```r
> V = readRDS('Y_variance.rds')
> tmp = solve(V)
Error in solve.default(V) : 
  system is computationally singular: reciprocal condition number = 3.06239e-18
> sum(diag(V))
[1] 6.50957e-05   
> sum(V)
[1] 6.50957e-05
```

**Comment by pcarbo** [comment]
The issue is that some variances are much larger than the others; running `solve(V*1e20)` still gives you the same error. To me these data look pretty weird—why are the variances so small?

**Comment by gaow** [comment]
It is simulated data where unfortunately in some conditions the effect ends up a lot larger than that in other conditions. Then for those condition with very small effects, forcing them to still have large PVE leads to small variance in the corresponding Y. Of course if I change simulation settings it will not be an issue. But generally speaking, in real data Y can come in at various scales from very small to very large that we have no control over. It is therefore reasonable to handle it one way or another: either just quit on error and let users check their data, or do something more complicated internally eg scale Y and prior before analyzing them.

**Comment by pcarbo** [comment]
I guess "standardizing" responses seems like a reasonable to do? glmnet provides this option but interestingly does not do this by default. It might be helpful to find out what other multivariate regression R packages do.

**Comment by fmorgante** [comment]
I think that glmnet always standardizes y. The choice the users have is whether standardizing X or not.

On Mar 3, 2020, at 7:48 AM, Peter Carbonetto <notifications@github.com> wrote:

﻿

I guess "standardizing" responses seems like a reasonable to do? glmnet provides this option but interestingly does not do this by default. It might be helpful to find out what other multivariate regression R packages do.

**Comment by pcarbo** [comment]
> I think that glmnet always standardizes y. The choice the users have is whether standardizing X or not.

Not in glmnet 3.0-2. These are the defaults:

```
standardize = TRUE
standardize.response = FALSE
```

The first standardizes X, the second standardizes Y.

**Comment by stephens999** [comment]
my gut is that we would want results of multivariate regression to be
invariant to any such rescaling.

So one could either do it or not, and it would not change the results
(but could change numerical stability).

But I guess that to get such invariance one would have to specify both
priors and residual variances
in an appropriately scaled form (like the scaled_prior_variance in
susie...) and this might make
add to the user cognitive burden....

So I'm not sure what is best here.

**Comment by pcarbo** [comment]
Seems like developing a proper interface to handle this is premature, and for now is better addressed on a case-by-case basis.

**Comment by stephens999** [comment]
yes, @gaow can you handle for now by simply rescaling Y manually before
input?

**Comment by gaow** [comment]
@stephens999 @pcarbo @fmorgante thanks for your feedback. I think we can manage internally the scaling of Y and prior, but not the residual variances. Then suppose users have `standardize.respose=T` and also provided residual variances, at this point we can give a warning, and additionally do some simple checks such as comparing if residual variances is greater than variance of Y.

**Comment by stephens999** [comment]
so the standardize response would not affect the results, only numerical
stability?

**Comment by stephens999** [comment]
by the way, are you sure solve is the right way to go?
Your example produces no problem for me with cholesky and backsolve...

tmp = backsolve(chol(V),rep(1,50))

**Comment by gaow** [comment]
> so the standardize response would not affect the results, only numerical
stability?

Yes. As you (your gut) said, scaling or not should not matter to results. In other words, users should not need to think about it. We could have just done it internally if not for the complications involved in prior and residual variance specifications. I guess that's why you said for now we dont implement any formal fixes to the issue but rely on handling Y properly as data preprocessing step.

> Your example produces no problem for me with cholesky and backsolve...

Please try this example : 

[issue_25.tar.gz](https://github.com/stephenslab/mmbr/files/4288063/issue_25.tar.gz)

```
> dat = readRDS('spd_issue.rds')
> tmp = backsolve(chol(dat$Vinv %*% dat$U),rep(1,50))
Error in chol.default(dat$Vinv %*% dat$U) : 
  the leading minor of order 2 is not positive definite
> 
```

The only I uploaded previously was meant to be a simpler demo. The actual error reported in my code was this line above. 

If we stick to `solve` with a lower `tol` to relax on the condition number tolerance, the code will run. But I do think this issue warrants more formal handling than that.

**Comment by stephens999** [comment]
not sure we want to compute Vinv...? generally one tries to avoid computing
matrix inverses.

**Comment by gaow** [comment]
See #30
