### ISSUE TITLE
Decreasing ELBO with prior scalar variance EM updates when combined with null check

### ISSUE THREAD

**Issue by gaow** [stephenslab/mmbr#26]
@pcarbo @stephens999 @zouyuxin here is the problem:

https://stephenslab.github.io/mmbr/prototypes/elbo_prior_est.html

(please read the first 3 sections if you don't have time to read the example). 

I think we do the same thing in SuSiE and perhaps is also problematic:

https://github.com/stephenslab/susieR/blob/af5dc7404034a969a540f1fc3325698de64c4553/R/single_effect_regression.R#L87

What do you think -- is this a valid concern, and should we just remove that comparison at the end of an EM update and call it a day? Or we do extra work at the end of convergence to check on single effect model loglik with zero prior in order to set prior to zero? The latter seems a messy approach ...  Or should we just threshold eg those estimated V < 1E-6 to zero by ignoring the corresponding single effect when computing PIP etc. after IBSS converges?

**Comment by pcarbo** [comment]
One point of clarification: the EM updates do not work (and are not expected to do so) when initialized with `sigma0 = 0`.

**Comment by gaow** [comment]
@pcarbo and I just discussed this offline:

1. For simpler case of multivariate normal prior `b ~ MVN(0, sigma^2 U)` we can potentially "escape" `sigma = 0` by using a different derivation. Current EM assumes two hidden variables, `b` and `gamma` but we don't need `b` in this case. This is similar to their recent work with the improved EM algorithm for Extreme Deconvolution. However our main goal is for the mixture prior case. The problem there remains. 
2. We confirmed that SuSiE EM update does potentially has the problem.
3. @pcarbo suggested that even setting sigma to a very small number, eg 1E-8, as long as it is not exactly zero we should be able to escape this trap. Indeed in #27 many sigma apparently are set to very small number eg 1E-9 but seems to work. The current EM update should not set it to zero anyways as long as we dont force it zero, as with current implementation.

**Comment by pcarbo** [comment]
Thanks for the summary @gaow. I should add that (3) is a commonly used workaround for the issue of getting "trapped" at a zero.

**Comment by stephens999** [comment]
i want to clarify there are two distinct issues:
i) EM, with check, does not increase ELBO
ii) EM has a fixed point at 0 

I would not say the EM updates "do not work" when initialized at 0. They
just stay where they are. In particular they do not decrease the objective.

More generally I do not understand why the ELBO decreases (when tolerance is set to 0 not 0.1).
Each EM update guarantees to not decrease. And the check also guarantees not to decrease...
So we are combining non-decreasing steps... it should never decrease if done properly. 
(Or possibly I misunderstand something?)

**Comment by pcarbo** [comment]
From what @gaow explained to me, I don't think there is any issue with the EM updates themselves—the EM updates never decrease the ELBO.

**Comment by gaow** [comment]
Okay I think we have established that the EM updates are fine at least from our observations. And that different from directly maximizing the loglik (optim + the check) and use the update in the current iteration, EM takes one step at a time and the resulting updated value will not be used until next iteration. I think given these difference it is no longer true that we are combining two non-decreasing steps for ELBO.

I have added a track for estimated prior which will be available as `fit$prior_history` if `track_fit = TRUE` in `msusie` function call. You can see that comparing prior history for EM with L = 10 vs L = 5:

https://stephenslab.github.io/mmbr/prototypes/elbo_prior_est.html#EM-method

It seems for L = 10 at the 2nd iteration, the loglik is better using zero than using updates from the first iteration.  So the first two effects are both set to zero. It is slightly different for L = 5. If I set `check_null_threshold = 0.1` for L = 5 then the ELBO will be non-decreasing!

Also notice that the update at the first EM step is different from the first iteration of optim,

https://stephenslab.github.io/mmbr/prototypes/elbo_prior_est.html#optim-method

**Comment by stephens999** [comment]
I don't fully understand why "...it is no longer true that we are combining
two non-decreasing steps for ELBO."
But if this is the case can we change it so that we *are* combining
non-decreasing steps?

If I understand, we can write the goal of this step to optimize F(q,s0)
where q is the variational posterior for this effect and s0 is the prior
hyperparameter.

The "optim" approach is to optimize F(q,s0) jointly over (q,s0). It does
this by noting that
if qhat(s0): = arg max_q F(q,s0)
then F(qhat(s0),s0) can be computed as a function of s0 - we call this
loglik(s0) by analogy with the code. That is,
loglik(s0): = max_q F(q,s0) [**]

So the optim approach is to find s0hat = arg max(loglik(s0)) and then set
qhat = qhat(s0hat).

The "EM" approach takes in a current (q,s0) and then maximizes q given
current s0 and then maximizes s0 given current q:
qnew <- max_q F(q,s0)
s0new <- max_s0 F(qnew, s0).
So this guarantees to increase objective F(qnew,s0new) >= F(q,s0)

Now the check step *should* be to check whether F(q0,s00) > F(qnew,s0new)
where s00 is null (s0=0) and q0 is corresponding posterior (also null).
if loglik(s00)>= loglik(s0new) then
F(q0,s00) = loglik(s00) >= loglik(s0new) >= F(qnew,s0new)
where the last follows from [**].

So the "check" should also increase F. Unless the problem is that you are
not updating q <-q0 when the check selects the null (s0=s00=0)?

**Comment by gaow** [comment]
> Unless the problem is that you are
not updating q <-q0 when the check selects the null (s0=s00=0)?

Yes exactly that's the point I wanted to make when I said that "the EM update in current iteration was not used until next update". As you said making sure we are combining these steps properly -- which is a bit messy for EM because you'll have to go back recomputing `q`. But I think we should either drop that check update, or do this properly even if it is messy ...

**Comment by stephens999** [comment]
i agree - do it right or don't do it.

**Comment by gaow** [comment]
Sorry I'm getting back to this today -- in order to do this "right", we will need to update `q <-q0` when the null is better; but at the same time we cannot simply set posterior quantities to, eg, 0s and all logBF to 1, because s0 = 0 is the fixpoint for EM it will get trapped. 

I think what has to happen is instead of checking with s0 = 0 for the null, we check with a small number, s0 = \epsilon, so EM would be trapped?

**Comment by pcarbo** [comment]
@gaow Looking back at this, I'm really not sure why this step is needed:

> Now the check step *should* be to check whether F(q0,s00) > F(qnew,s0new)

Why not just let (variational) EM do its thing, and let it figure out what is the best qnew, s0new? If the best solution is the "null" solution, EM should be able to figure that out by setting s0new to a small value.

**Comment by gaow** [comment]
> If the best solution is the "null" solution, EM should be able to figure that out by setting s0new to a small value.

@pcarbo I think @stephens999 was suggesting that combining two non-decreasing steps properly should only help with ELBO and make it converge faster. Practically speaking, we also want some "check" on zero to eliminate some null single effects when we set `L` too large. Otherwise I would agree with not checking with zero.

But my concern is what if in the first iteration, loglik(s0_optim) > loglik(0) but loglik(s0_em) < loglik(0). Then if we let EM do its job it eventually in later iterations will get to the point that loglik(s0_em_later) > loglik(0). But setting s0_em = 0 too early eliminates this possibility so it doesn't seem the best thing to do. Setting it to s0_em = \epsilon can still help making convergence faster, but in the end all effects will have non-zero prior estimate and if we want to eliminate the number of non-zero effects we've got to use some heuristics; or to compare s0_em with 0 one more time after all iterations ...

**Comment by pcarbo** [comment]
> Practically speaking, we also want some "check" on zero to eliminate some null single effects when we set L too large. 

Yes, I understand this. But it seems to me that updating sigma0 via EM is sufficient to accomplish this; i.e., the effect will be eliminated if EM estimates sigma0 to be zero (or a small number).

**Comment by gaow** [comment]
>  updating sigma0 via EM is sufficient to accomplish this

This is only true if we set some cutoff on sigma0 at the end to filter ... which we can do.

Also EM without check zero can converge slower although we will have to see how much slower in general, using simulations.

**Comment by pcarbo** [comment]
We don't know how quickly the EM updates will recover a zero, or small, sigma0, that is true.

**Comment by stephens999** [comment]
just circling back on this.

i) I think we should remove any options that might sometimes 
decrease the ELBO during iterations. eg
with the tolerance=0.1 we introduced previously - I think that was a mistake with hindsight. 
Instead, if users want to trim out "negligible" components, let's provide a function to do that at the end (eg in susie, a susie_trim function that can be applied to the fit in susie).

ii) I am OK with including a null check option, appropriately implemented, as part of the EM algorithm. It may or may not increase/decrease speed and increase/decrease final ELBO (but it should not decrease ELBO during iterations.) I'm not so keen on having a null check against epsilon though - too many complications. If we do the null check then I think we just accept it can get stuck at 0. That could be good or bad in terms of both speed and performance...We can assess this.

iii) I'll also mention another option/complication - even with nullcheck, it might be good to do a few (5-10) iterations of EM without the nullcheck first...

**Comment by gaow** [comment]
> Instead, if users want to trim out "negligible" components, let's provide a function to do that at the end (eg in susie, a susie_trim function that can be applied to the fit in susie).

We have `susie_get_pip` function that currently has a built in filter for prior variance < 1E-9 to iron this out. We can make that configurable? 

> I am OK with including a null check option, appropriately implemented, as part of the EM algorithm.

"appropriately implemented" means we update `q <-q0` when the check selects the null, even if this is premature to set it to zero? 

The code currently is there but is commented out. We can bring it back but adding an option can be tricky -- we only have one parameter for optimization method. How about still using `estimate_prior_method = ...` option but use `EM` and `EM-something` for versions with&without check? eg, `EM_check_null`? 

> even with nullcheck, it might be good to do a few (5-10) iterations of EM without the nullcheck first...

We definitely can do this -- without a user option for it though?

And what do you suggest we set the default to? `EM_check_null` starting from 5+ iterations seems an appealing default. Or, we can benchmark it and see ...

**Comment by stephens999** [comment]
On Mon, Apr 13, 2020 at 10:41 AM gaow <notifications@github.com> wrote:

> Instead, if users want to trim out "negligible" components, let's provide
> a function to do that at the end (eg in susie, a susie_trim function that
> can be applied to the fit in susie).
>
> We have susie_get_pip function that currently has a built in filter for
> prior variance < 1E-9 to iron this out. We can make that configurable?
>
> I am OK with including a null check option, appropriately implemented, as
> part of the EM algorithm.
>
> "appropriately implemented" means we update q <-q0 when the check selects
> the null, even if this is premature to set it to zero?
>
> yes.

The code currently is there but is commented out. We can bring it back but
> adding an option can be tricky -- we only have one parameter for
> optimization method. How about still using estimate_prior_method = ...
> option but use EM and EM-something for versions with&without check? eg,
> EM_check_null?
>
> even with nullcheck, it might be good to do a few (5-10) iterations of EM
> without the nullcheck first...
>
> We definitely can do this -- without a user option for it though?
>
> I think it is perhaps premature to decide on user options. But yes, for
our own purposes it seems we
can (and should) benchmark two versions, one with check and the other
without.
And I would suggest the one with the check only implements the check after
10 iterations of regular EM... we could
experiment with that, but let's start with that and then benchmark the 2
approaches (no check vs check after 10 iterations).

Matthew

**Comment by gaow** [comment]
I implemented this interface for now: 

1. EM without check with zero: `msusie(..., estimate_prior_method='EM', check_null_threshold=NA, ...)`
2. EM and check with zero after 10 iterations: `msusie(..., estimate_prior_method='EM', ...)` this will use the default `check_null_threshold=0`.

**Comment by gaow** [comment]
> Instead, if users want to trim out "negligible" components, let's provide a function to do that at the end (eg in susie, a susie_trim function that can be applied to the fit in susie).

Now, `susie_get_pip` function takes a parameter `prior_tol` with default set to `1E-9`. Setting this to larger number will trim those negligible components. `prior_tol` parameter is also added to `susieR::susie`, `susieR::susie_rss`, `susieR::susie_sum_stats`, and `mmbr::msusie` and `mmbr::msusie_rss`.
