### ISSUE TITLE
Various input scaling issues

### ISSUE THREAD

**Issue by gaow** [stephenslab/mmbr#30]
Currently in both `susieR` and `mmbr` we have center and scale for `X`. There are a number of things that we might want to consider adding to scale:

1. `Y` and `residual_variance`: in current version of `glm.net` there is an option `standardize.respose`. The problem here is that we don't know if the input prior is based on scaled data or not. This makes it difficult to also make adjustment (or not make any!) to prior.
2. We have `s_init` in `susieR::susie` and `mmbr::msusie` interfaces to initialize with a previous fit. The initialization uses not the estimated coefficient -- which is scaled back to original scale after IBSS is done -- but uses the single effect model fits, that is, those marginal first and second moments for each single effect model L, to initialize. These quantities, available in susieR/mmbr output as `$b1` and `$b2` are not scaled back to the original. Therefore if we use them to initialize another `susie/msusie` run but with different setting of `standardize= ...` they will be the wrong initialization. 

I propose that:

1. We still provide `standardize.response` anyways, and use that to scale `Y` and `residual_variance`. We set the default to `FALSE`.
2. If users provide some fixed prior, we will not say anything but using those prior without adjustment, assuming the users know what they are doing. But if no prior is specified and default mixture of canonical prior is used, we might want to ask users to think of scale of `Y`; because canonical prior as we implemented in MASH implicitly assumes Y is scaled.  In that case a warning message should be given.
3. For consistency we might also want to add `standardize.response` to `susieR`?
4. In the output object in susieR/mmbr we might want to also scale back the first and second moments. And when they are used to initialize we need to scale them based on whether or not the input is being asked to scale. 

@fmorgante asked me about the scaling for initialization using fitted model. Of course the above assumes complete data without missing elements in `Y`.

**Comment by stephens999** [comment]
i'd suggest not adding the option to standardize response. The user can do
that or not as they prefer.
I don't see any benefit to adding it, and it just increases complexity.

**Comment by gaow** [comment]
@stephens999 by the same token, should we **always** ask users to provide fixed prior (an R by R matrix or a mixture of R by R matrices) so they will be responsible to think about scaling issues? That is, we don't default prior to canonical mixture when no prior is provided? In that case users will be completely responsible for scaling. For example if these priors are learned from ED pipeline then users should ensure the scaling is consistent with when they are learned. If they want to use canonical mixture they should scale `Y` in the analysis. 

We will need to use vignettes to deliver these points, although we can provide a workflow script (eg using SoS / snakemake) that implements a version of it with consistent scaling, for those who wants to run it as a black box, or for those who understand what's going on but still looking for a quick standard run.

**Comment by stephens999** [comment]
no, i think we should provide a sensible default. We should be able to do that.
eg We can scale the prior by variance of Y, or internally scale Y.

**Comment by gaow** [comment]
> We can scale the prior by variance of Y

This option was implemented.
