### ISSUE TITLE
Prune duplicated variables in X matrix and add them back after

### ISSUE THREAD

**Issue by gaow** [stephenslab/mmbr#31]
In `atlasqtl` completely identical SNPs are removed beforehand; results are reported on the pruned set along with what SNPs are removed due to complete LD with what SNP that remains.

We can do the same in susieR / mmbr. I was not very motivated before because these software are fast enough, and computing LD then removing them seems messy. However I am more motivated at this point because:

1. From email correspondence with a susieR user, she claims that in a mouse data-set, susieR was only able to find causal SNPs in 5 out of 40 loci that are GWAS significant. However after removing duplicates, susieR can recover more than 30 out of 40 signals. Although this does not sound right in principle (and I'll follow up on getting the data to see for myself), it is plausible that removing duplicates might help avoiding numerical issues
2. mvSuSiE can get quite computational intensive when EM is used to estimate prior scalar; and when missing data related computations are involved. Complexity are at least linear to number of variables. 

It is perhaps worth implementing them. I think I'll code it in `susieR` and import those functions to `mmbr`. For now I'm going to do this only for full data version.

**Comment by stephens999** [comment]
how much does this reduce number of SNPs? It seems it is unlikely to be a
big speed up?

**Comment by gaow** [comment]
@stephens999 in a couple of GTEx based example (including one we used for the manuscript, and another one I uploaded as a test data), we'll remove 10% and 18% SNPs respectively if we filter out those in complete LD. So it will reduce that much of computation for @zouyuxin current missing data version. For full data case, the result should be the same with and without removing duplicates. Up to 20% performance gain might be useful. What's the harm do you think there is, for full data version?

It becomes a bit tricky for RSS version because the LD reference panel might be wrong, or slightly off. For example we can have a problem if two SNPs have R = 1 in the reference but slightly different z scores. The problem can be "fixed" if we just remove one of those SNPs based on complete LD (and randomly drop one z-score). That is what we suspect the reason for the user's improved result (it is not clear to us whether she really used in-sample LD or something slightly off). This "fix" in the context of RSS, albeit incorrect, can at the face value is a relatively simply approach to obtain what looks more reasonable result.

**Comment by stephens999** [comment]
it's an extra complication.. not convinced it is worth it for 20%
performance gain.

**Comment by gaow** [comment]
@stephens999 okay, i'll hold that off. I did implement the functions to [remove](https://github.com/stephenslab/mmbr/blob/798994fadb38bc30ba84e79ac647d81d42f0cf1f/R/utils.R#L179) and to [add back](https://github.com/stephenslab/mmbr/blob/798994fadb38bc30ba84e79ac647d81d42f0cf1f/R/utils.R#L220) duplicates, in case we want to revisit down the road. Lets just leave these functions in `utils.R` of mmbr for now.
