### ISSUE TITLE
issues with intializing dataset

### ISSUE THREAD

**Issue by bhattacharya-a-bt** [stephenslab/mmbr#33]
I'm running into the following error (which I assume is an initialization problem with the DenseData structure):

Error in colSums(.X^2) : 'x' must be an array of at least two dimensions

Code is attached. Any help would be appreciated.

[test_mmbr.zip](https://github.com/stephenslab/mmbr/files/5961858/test_mmbr.zip)

**Comment by gaow** [comment]
@bhattacharya-a-bt thanks for the error report. We just got a chance to look into this. Not sure why you had to convert the matrix to a sparse one, but we figure it might be a misleading error message on our end which we have fixed in the patch above. Also problematic in your code is that you did not specify a prior. 

Could you try to install the current `master` of mmbr and use these two lines to run the core analysis:

```r
    prior_covar = mmbr::create_mash_prior(sample_data = list(X=X.tr,Y=Y.tr,residual_variance=cov(Y.tr)), max_mixture_len=-1)
    m <- mmbr::msusie(X = X.tr,
                      Y = Y.tr,
		      prior_variance=prior_covar,
                      L = 10)
```

Unless there are other reasons you use sparse X in which case please let us know.

**Comment by bhattacharya-a-bt** [comment]
Still running into issues with create_mash_prior(). Here's the error
message:

Error in get(name, envir = asNamespace(pkg), inherits = FALSE) :  object
'issemidef' not found.

Thanks for all your help.

**Comment by gaow** [comment]
@bhattacharya-a-bt could you update to the current [`master` of `mashr` package](https://github.com/stephenslab/mashr)? (the cran version of `mashr` is not up to date and we are waiting to tie up some loose ends before we update on cran.)

**Comment by bhattacharya-a-bt** [comment]
I'm getting issues when installing the latest version of mashr, but it
seems to be an issue with RcppGSL:

C:/Users/Arjun/Documents/R/win-library/4.0/RcppGSL/include/RcppGSLForward.h:25:10:
fatal error: gsl/gsl_vector.h: No such file or directory
 #include <gsl/gsl_vector.h>

Any ideas how to resolve this?

**Comment by gaow** [comment]
@bhattacharya-a-bt  I dont have the particular experience to install GSL libraries on Windows and connect that to R ... on Linux and Mac those are straightforward (not sharing the solutions for lack of relevance) but if you search online there should be tips for Windows? For example, https://stackoverflow.com/questions/55976547/linking-gsl-libraries-to-rcppgsl-in-windows-10

**Comment by bhattacharya-a-bt** [comment]
Yeah - got it. I guess it's not necessary to install this on my Windows
machine. Seems like it's working on my Linux machine, so should be good to
go. Thanks a lot!
